AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the AWS::NetworkManager::CoreNetwork resource type

Globals:
  Function:
    Timeout: 480  # docker start-up times can be long for SAM CLI
    MemorySize: 1024

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.amazonaws.networkmanager.corenetwork.HandlerWrapper::handleRequest
      Runtime: java8
      CodeUri: ./target/aws-networkmanager-corenetwork-1.0.jar

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.amazonaws.networkmanager.corenetwork.HandlerWrapper::testEntrypoint
      Runtime: java8
      CodeUri: ./target/aws-networkmanager-corenetwork-1.0.jar
